name = "link-collector-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
APP_PASSWORD = "123456"
SENSENOVA_API_KEY = "sk-BuUTAgqxXbKWKfJK6lTFBDazA5HbIMUf"
FEISHU_APP_ID = "cli_a95dd9f9a1fa1bde"
FEISHU_APP_SECRET = "2CXxbqV1DNa7wgL0aXa3YbZfwgPfRVIC"
FEISHU_BASE_APP_TOKEN = "S0yqbYKZfaAdjdsxoE9cbObQn3f"
FEISHU_BASE_TABLE_ID = "tbldFGPSao1S5evS"
