name = "link-collector-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
APP_PASSWORD = "123456"
SENSENOVA_API_KEY = ""
FEISHU_APP_ID = ""
FEISHU_APP_SECRET = ""
FEISHU_BASE_APP_TOKEN = ""
FEISHU_BASE_TABLE_ID = ""
